[azure]
symbol = "󰠅 "
format = 'on [$symbol($subscription)]($style) '
style = "bold fg:#00ff00"

[kubernetes]
symbol = "☸ "
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)]($style) '
style = "bold fg:#00ff00"
disabled = false

# --- SAFETY ALARMS ---
[[kubernetes.contexts]]
context_pattern = "(?i).*prod.*"
style = "bold bg:#00ff00 fg:#000000" 

[[kubernetes.contexts]]
context_pattern = "(?i).*(staging|uat).*"
style = "bold fg:#00aa00" 

[aws]
symbol = "☁️  "
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold fg:#00aa00"

# --- TIME MODULE ---
[time]
disabled = false
time_format = "%I:%M %p" # Shows 12-hour format (e.g., 03:15 PM)
style = "bold fg:#ff8800"
format = '[\[$time\]]($style) '

# --- CUSTOM CPU MODULE (macOS) ---
[custom.cpu]
# This command adds up the CPU usage of all running processes and divides it by your Mac's core count
command = "ps -A -o %cpu | awk -v cores=$(sysctl -n hw.ncpu) '{s+=$1} END {printf(\"%.0f%%\", s/cores)}'"
when = "true"
style = "bold red"
format = '[💀 $output]($style) '